const MFASetupPage = () => (
  <div className="auth-page">
    <div className="auth-card mfa-card">
      <div className="mfa-icon">🔐</div>
      <h1 className="auth-title">Setup MFA</h1>
      <p className="auth-subtitle">Secure your account with two-factor authentication</p>

      <ul className="mfa-steps">
        <li>
          <span className="step-num">1</span>
          Install <strong style={{ color: 'var(--text)' }}>Google Authenticator</strong> or <strong style={{ color: 'var(--text)' }}>Authy</strong> on your phone
        </li>
        <li>
          <span className="step-num">2</span>
          Open the app and tap <strong style={{ color: 'var(--text)' }}>Scan QR Code</strong>
        </li>
        <li>
          <span className="step-num">3</span>
          Scan the placeholder code below - a real QR is generated by the backend.
        </li>
        <li>
          <span className="step-num">4</span>
          Click <strong style={{ color: 'var(--text)' }}>Activate MFA</strong> to complete setup
        </li>
      </ul>

      <div style={{ textAlign: 'center' }}>
        <div className="qr-wrapper">
          <img src="https://via.placeholder.com/180?text=Scan+to+Link" alt="QR Code" />
        </div>
      </div>

      <p className="auth-subtitle" style={{ color: '#888', fontSize: '0.85rem', marginBottom: '8px' }}>
        Open the Flask backend's /setup-mfa route to generate a real QR code.
      </p>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 10, marginTop: 8 }}>
        <a href="/activate-mfa" className="btn-gold form-btn" style={{ textAlign: 'center' }}>
          <i className="fa fa-shield-halved me-2"></i>Activate MFA
        </a>
        <a href="/home" className="btn-outline form-btn" style={{ textAlign: 'center' }}>
          <i className="fa fa-forward-step me-2"></i>Skip for Now
        </a>
      </div>
    </div>
  </div>
);

export default MFASetupPage;
